import * as SC2 from "../SC2";

export const Core6 = SC2.makeHotkeyProfile([
  [SC2.ABILITIES.cancel, "7"],
  [SC2.ABILITIES.attack, ";"],
  [SC2.ABILITIES.holdPosition, "'"],
  [SC2.ABILITIES.stop, "."],
  [SC2.ABILITIES.patrol, "y"],
  [SC2.ABILITIES.build, "k"],
  [SC2.ABILITIES.build, "p"],
  [SC2.ABILITIES.buildAdvanced, "/"],
  [SC2.ABILITIES.load, "."],
  [SC2.ABILITIES.unloadAll, "/"],
  [SC2.ABILITIES.returnCargo, "-"],
  [SC2.ABILITIES.gather, "="],
  [SC2.ABILITIES.spray, "back"],

  /*
   * TERRAN
   */
  [SC2.UNITS.scv, "p"],
  [SC2.UNITS.marine, ";"],
  [SC2.UNITS.marauder, "p"],
  [SC2.UNITS.reaper, "/"],
  [SC2.UNITS.ghost, "'"],
  [SC2.UNITS.hellion, ";"],
  [SC2.UNITS.widowMine, "p"],
  [SC2.UNITS.siegeTank, "/"],
  [SC2.UNITS.thor, "'"],
  [SC2.UNITS.cyclone, "."],
  [SC2.UNITS.hellbat, "-"],
  [SC2.UNITS.viking, ";"],
  [SC2.UNITS.liberator, "p"],
  [SC2.UNITS.medivac, "/"],
  [SC2.UNITS.raven, "'"],
  [SC2.UNITS.banshee, "."],
  [SC2.UNITS.battlecruiser, "-"],

  [SC2.BUILDINGS.missileTurret, ";"],
  [SC2.BUILDINGS.supplyDepot, "k"],
  [SC2.BUILDINGS.barracks, "p"],
  [SC2.BUILDINGS.refinery, "/"],
  [SC2.BUILDINGS.bunker, "["],
  [SC2.BUILDINGS.engineeringBay, "'"],
  [SC2.BUILDINGS.sensorTower, "."],
  [SC2.BUILDINGS.commandCenter, "-"],
  [SC2.BUILDINGS.starport, ";"],
  [SC2.BUILDINGS.factory, "k"],
  [SC2.BUILDINGS.ghostAcademy, "p"],
  [SC2.BUILDINGS.armory, "'"],
  [SC2.BUILDINGS.fusionCore, "."],

  [SC2.ABILITIES.buildReactor, "k"],
  [SC2.ABILITIES.buildTechLab, "["],
  [SC2.ABILITIES.liftOff, "]"], // land uses the same key
  [SC2.ABILITIES.stimpack, "k"],
  [SC2.ABILITIES.cloak, "["],
  [SC2.ABILITIES.decloak, "]"],

  [SC2.BUILDINGS.bunker.abilities.salvage, "p"],
  [SC2.BUILDINGS.commandCenter.abilities.load, "\\"],
  [SC2.BUILDINGS.commandCenter.abilities.orbitalCommand, ";"],
  [SC2.BUILDINGS.commandCenter.abilities.planetaryFortress, "k"],
  [SC2.BUILDINGS.orbitalCommand.abilities.calldownMule, ";"],
  [SC2.BUILDINGS.orbitalCommand.abilities.scan, "k"],
  [SC2.BUILDINGS.orbitalCommand.abilities.supplyDrop, "/"],
  [SC2.BUILDINGS.supplyDepot.abilities.raise, "k"],
  [SC2.BUILDINGS.supplyDepot.abilities.lower, "p"],

  [SC2.UPGRADES.infantryWeapons, ";"],
  [SC2.UPGRADES.infantryArmor, "k"],
  [SC2.UPGRADES.hisecAutoTracking, "p"],
  [SC2.UPGRADES.neosteelArmor, "["],
  [SC2.UPGRADES.vehicleWeapons, ";"],
  [SC2.UPGRADES.vehiclePlating, "k"],
  [SC2.UPGRADES.shipWeapons, "p"],
  [SC2.UPGRADES.stimpack, ";"],
  [SC2.UPGRADES.concussiveShells, "k"],
  [SC2.UPGRADES.combatShield, "p"],
  [SC2.UPGRADES.infernalPreigniter, ";"],
  [SC2.UPGRADES.drillingClaws, "k"],
  [SC2.UPGRADES.smartServos, "p"],
  [SC2.UPGRADES.hurricaneEngines, "["],
  [SC2.UPGRADES.interferenceMatrix, ";"],
  [SC2.UPGRADES.hyperflightRotors, "k"],
  [SC2.UPGRADES.cloakingField, "["],
  [SC2.UPGRADES.armNuke, ";"],
  [SC2.UPGRADES.personalCloaking, "["],
  [SC2.UPGRADES.advancedBallistics, "k"],
  [SC2.UPGRADES.weaponRefit, "p"],
  [SC2.UPGRADES.caduceusReactor, "/"],

  [SC2.UNITS.scv.abilities.repair, "["],
  [SC2.UNITS.battlecruiser.abilities.tacticalJump, "k"],
  [SC2.UNITS.battlecruiser.abilities.tacticalJump, "["],
  [SC2.UNITS.battlecruiser.abilities.yamatoCannon, "p"],
  [SC2.UNITS.cyclone.abilities.lockOn, "k"],
  [SC2.UNITS.cyclone.abilities.lockOn, "p"],
  [SC2.UNITS.ghost.abilities.emp, "k"],
  [SC2.UNITS.ghost.abilities.holdFire, "/"],
  [SC2.UNITS.ghost.abilities.snipe, "p"],
  [SC2.UNITS.ghost.abilities.weaponsFree, "-"],
  [SC2.UNITS.ghost.abilities.nukeCalldown, "="],
  [SC2.UNITS.hellion.abilities.toHellbat, "k"],
  [SC2.UNITS.hellion.abilities.toHellion, "p"],
  [SC2.UNITS.liberator.abilities.defender, "k"],
  [SC2.UNITS.liberator.abilities.fighter, "p"],
  [SC2.UNITS.liberator.abilities.defender, "["],
  [SC2.UNITS.medivac.abilities.afterburners, "k"],
  [SC2.UNITS.medivac.abilities.heal, "["],
  [SC2.UNITS.raven.abilities.interferenceMatrix, "k"],
  [SC2.UNITS.raven.abilities.autoturret, "p"],
  [SC2.UNITS.raven.abilities.antiArmorMissile, "["],
  [SC2.UNITS.reaper.abilities.kd8Charge, "k"],
  [SC2.UNITS.reaper.abilities.kd8Charge, "p"],
  [SC2.UNITS.siegeTank.abilities.siegeMode, "k"],
  [SC2.UNITS.siegeTank.abilities.tankMode, "p"],
  [SC2.UNITS.thor.abilities.highImpactPayload, "k"],
  [SC2.UNITS.thor.abilities.explosivePayload, "p"],
  [SC2.UNITS.viking.abilities.assaultMode, "k"],
  [SC2.UNITS.viking.abilities.fighterMode, "p"],
  [SC2.UNITS.widowMine.abilities.burrow, "k"],
  [SC2.UNITS.widowMine.abilities.unburrow, "p"],




  [SC2.ABILITIES.burrow, "["],
  [SC2.ABILITIES.unburrow, "]"],

  [SC2.UNITS.zergling, ";"],
  [SC2.UNITS.baneling.abilities.explode, "f"],
]);
