import * as SC2 from "../SC2";

export const Core6 = SC2.makeHotkeyProfile([
  [SC2.ABILITIES.cancel, "7"],
  [SC2.ABILITIES.attack, ";"],
  [SC2.ABILITIES.holdPosition, "'"],
  [SC2.ABILITIES.stop, "."],
  [SC2.ABILITIES.patrol, "y"],
  [SC2.ABILITIES.build, "k"],
  [SC2.ABILITIES.build, "p"],
  [SC2.ABILITIES.buildAdvanced, "/"],
  [SC2.ABILITIES.load, "."],
  [SC2.ABILITIES.unloadAll, "/"],
  [SC2.ABILITIES.returnCargo, "-"],
  [SC2.ABILITIES.gather, "="],
  [SC2.ABILITIES.spray, "back"],
  // [SC2.ABILITIES.setRallyPoint, ""],

  /*
   * TERRAN
   */
  [SC2.UNITS.scv, "p"],
  [SC2.UNITS.marine, ";"],
  [SC2.UNITS.marauder, "p"],
  [SC2.UNITS.reaper, "/"],
  [SC2.UNITS.ghost, "'"],
  [SC2.UNITS.hellion, ";"],
  [SC2.UNITS.widowMine, "p"],
  [SC2.UNITS.siegeTank, "/"],
  [SC2.UNITS.thor, "'"],
  [SC2.UNITS.cyclone, "."],
  [SC2.UNITS.hellbat, "-"],
  [SC2.UNITS.viking, ";"],
  [SC2.UNITS.liberator, "p"],
  [SC2.UNITS.medivac, "/"],
  [SC2.UNITS.raven, "'"],
  [SC2.UNITS.banshee, "."],
  [SC2.UNITS.battlecruiser, "-"],

  [SC2.BUILDINGS.missileTurret, ";"],
  [SC2.BUILDINGS.supplyDepot, "k"],
  [SC2.BUILDINGS.barracks, "p"],
  [SC2.BUILDINGS.refinery, "/"],
  [SC2.BUILDINGS.bunker, "["],
  [SC2.BUILDINGS.engineeringBay, "'"],
  [SC2.BUILDINGS.sensorTower, "."],
  [SC2.BUILDINGS.commandCenter, "-"],
  [SC2.BUILDINGS.starport, ";"],
  [SC2.BUILDINGS.factory, "k"],
  [SC2.BUILDINGS.ghostAcademy, "p"],
  [SC2.BUILDINGS.armory, "'"],
  [SC2.BUILDINGS.fusionCore, "."],

  [SC2.ABILITIES.buildReactor, "k"],
  [SC2.ABILITIES.buildTechLab, "["],
  [SC2.ABILITIES.liftOff, "]"],
  // [SC2.ABILITIES.land, "]"],
  [SC2.ABILITIES.stimpack, "k"],
  [SC2.ABILITIES.cloak, "["],
  [SC2.ABILITIES.decloak, "]"],

  [SC2.BUILDINGS.bunker.abilities.salvage, "p"],
  [SC2.BUILDINGS.commandCenter.abilities.load, "\\"],
  [SC2.BUILDINGS.commandCenter.abilities.orbitalCommand, ";"],
  [SC2.BUILDINGS.commandCenter.abilities.planetaryFortress, "k"],
  [SC2.BUILDINGS.orbitalCommand.abilities.calldownMule, ";"],
  [SC2.BUILDINGS.orbitalCommand.abilities.scan, "k"],
  [SC2.BUILDINGS.orbitalCommand.abilities.supplyDrop, "/"],
  [SC2.BUILDINGS.supplyDepot.abilities.raise, "k"],
  [SC2.BUILDINGS.supplyDepot.abilities.lower, "p"],

  [SC2.UPGRADES.infantryWeapons, ";"],
  [SC2.UPGRADES.infantryArmor, "k"],
  [SC2.UPGRADES.hisecAutoTracking, "p"],
  [SC2.UPGRADES.neosteelArmor, "["],
  [SC2.UPGRADES.vehicleWeapons, ";"],
  [SC2.UPGRADES.vehiclePlating, "k"],
  [SC2.UPGRADES.shipWeapons, "p"],
  [SC2.UPGRADES.stimpack, ";"],
  [SC2.UPGRADES.concussiveShells, "k"],
  [SC2.UPGRADES.combatShield, "p"],
  [SC2.UPGRADES.infernalPreigniter, ";"],
  [SC2.UPGRADES.drillingClaws, "k"],
  [SC2.UPGRADES.smartServos, "p"],
  [SC2.UPGRADES.hurricaneEngines, "["],
  [SC2.UPGRADES.interferenceMatrix, ";"],
  [SC2.UPGRADES.hyperflightRotors, "k"],
  [SC2.UPGRADES.cloakingField, "["],
  [SC2.UPGRADES.armNuke, ";"],
  [SC2.UPGRADES.personalCloaking, "["],
  [SC2.UPGRADES.advancedBallistics, "k"],
  [SC2.UPGRADES.weaponRefit, "p"],
  [SC2.UPGRADES.caduceusReactor, "/"],

  [SC2.UNITS.scv.abilities.repair, "["],
  [SC2.UNITS.battlecruiser.abilities.tacticalJump, "k"],
  [SC2.UNITS.battlecruiser.abilities.tacticalJump, "["],
  [SC2.UNITS.battlecruiser.abilities.yamatoCannon, "p"],
  [SC2.UNITS.cyclone.abilities.lockOn, "k"],
  [SC2.UNITS.cyclone.abilities.lockOn, "p"],
  [SC2.UNITS.ghost.abilities.emp, "k"],
  [SC2.UNITS.ghost.abilities.holdFire, "/"],
  [SC2.UNITS.ghost.abilities.snipe, "p"],
  [SC2.UNITS.ghost.abilities.weaponsFree, "-"],
  [SC2.UNITS.ghost.abilities.nukeCalldown, "="],
  [SC2.UNITS.hellion.abilities.toHellbat, "k"],
  [SC2.UNITS.hellion.abilities.toHellion, "p"],
  [SC2.UNITS.liberator.abilities.defender, "k"],
  [SC2.UNITS.liberator.abilities.fighter, "p"],
  [SC2.UNITS.liberator.abilities.defender, "["],
  [SC2.UNITS.medivac.abilities.afterburners, "k"],
  [SC2.UNITS.medivac.abilities.heal, "["],
  [SC2.UNITS.raven.abilities.interferenceMatrix, "k"],
  [SC2.UNITS.raven.abilities.autoturret, "p"],
  [SC2.UNITS.raven.abilities.antiArmorMissile, "["],
  [SC2.UNITS.reaper.abilities.kd8Charge, "k"],
  [SC2.UNITS.reaper.abilities.kd8Charge, "p"],
  [SC2.UNITS.siegeTank.abilities.siegeMode, "k"],
  [SC2.UNITS.siegeTank.abilities.tankMode, "p"],
  [SC2.UNITS.thor.abilities.highImpactPayload, "k"],
  [SC2.UNITS.thor.abilities.explosivePayload, "p"],
  [SC2.UNITS.viking.abilities.assaultMode, "k"],
  [SC2.UNITS.viking.abilities.fighterMode, "p"],
  [SC2.UNITS.widowMine.abilities.burrow, "k"],
  [SC2.UNITS.widowMine.abilities.unburrow, "p"],



  /*
   * PROTOSS
   */
  [SC2.UNITS.probe, "p"],
  [SC2.UNITS.zealot, ";"],
  [SC2.UNITS.stalker, "p"],
  [SC2.UNITS.adept, "/"],
  [SC2.UNITS.darkTemplar, "["],
  [SC2.UNITS.highTemplar, "'"],
  [SC2.UNITS.sentry, "."],
  [SC2.UNITS.immortal, ";"],
  [SC2.UNITS.observer, "p"],
  [SC2.UNITS.warpPrism, "/"],
  [SC2.UNITS.disruptor, "["],
  [SC2.UNITS.colossus, "'"],
  [SC2.UNITS.phoenix, ";"],
  [SC2.UNITS.oracle, "p"],
  [SC2.UNITS.voidRay, "/"],
  [SC2.UNITS.tempest, "["],
  [SC2.UNITS.carrier, "."],
  [SC2.UNITS.mothership, "'"],

  [SC2.BUILDINGS.photonCannon, ";"],
  [SC2.BUILDINGS.pylon, "k"],
  [SC2.BUILDINGS.gateway, "p"],
  [SC2.BUILDINGS.assimilator, "/"],
  [SC2.BUILDINGS.shieldBattery, "["],
  [SC2.BUILDINGS.forge, "'"],
  [SC2.BUILDINGS.cyberneticsCore, "."],
  [SC2.BUILDINGS.nexus, "-"],
  [SC2.BUILDINGS.stargate, ";"],
  [SC2.BUILDINGS.roboticsFacility, "k"],
  [SC2.BUILDINGS.templarArchive, "p"],
  [SC2.BUILDINGS.darkShrine, "["],
  [SC2.BUILDINGS.twilightCouncil, "'"],
  [SC2.BUILDINGS.fleetBeacon, "."],
  [SC2.BUILDINGS.roboticsBay, "-"],

  [SC2.ABILITIES.mergeArchon, "p"],

  [SC2.BUILDINGS.nexus.abilities.strategicRecall, ";"],
  [SC2.BUILDINGS.nexus.abilities.strategicRecall, "k"],
  [SC2.BUILDINGS.nexus.abilities.chronoBoost, "/"],
  [SC2.BUILDINGS.nexus.abilities.batteryOvercharge, "["],

  [SC2.UPGRADES.protossGroundWeapons, ";"],
  [SC2.UPGRADES.protossGroundArmor, "k"],
  [SC2.UPGRADES.protossShields, "p"],
  [SC2.UPGRADES.protossAirWeapons, ";"],
  [SC2.UPGRADES.protossAirArmor, "k"],
  [SC2.UPGRADES.warpgate, "p"],
  [SC2.UPGRADES.anionPulseCrystals, ";"],
  [SC2.UPGRADES.fluxVanes, "k"],
  [SC2.UPGRADES.tectonicDestabilizers, "p"],
  [SC2.UPGRADES.graviticBoosters, ";"],
  [SC2.UPGRADES.extendedThermalLance, "k"],
  [SC2.UPGRADES.graviticDrive, "p"],
  [SC2.UPGRADES.psionicStorm, "k"],
  [SC2.UPGRADES.charge, ";"],
  [SC2.UPGRADES.blink, "p"],
  [SC2.UPGRADES.resonatingGlaives, "/"],

  [SC2.UNITS.zealot.abilities.charge, "k"],
  [SC2.UNITS.zealot.abilities.charge, "["],
  [SC2.UNITS.adept.abilities.psionicTransfer, "k"],
  [SC2.UNITS.sentry.abilities.forceField, "k"],
  [SC2.UNITS.sentry.abilities.hallucination, "p"],
  [SC2.UNITS.sentry.abilities.hallucination, "/"],
  [SC2.UNITS.sentry.abilities.guardianShield, "["],
  [SC2.UNITS.stalker.abilities.blink, "k"],
  [SC2.UNITS.darkTemplar.abilities.shadowStride, "k"],
  [SC2.UNITS.highTemplar.abilities.psiStorm, "k"],
  [SC2.UNITS.highTemplar.abilities.feedback, "["],
  [SC2.UNITS.observer.abilities.surveillanceMode, "k"],
  [SC2.UNITS.observer.abilities.observerMode, "p"],
  [SC2.UNITS.warpPrism.abilities.phasingMode, "k"],
  [SC2.UNITS.warpPrism.abilities.transportMode, "p"],
  [SC2.UNITS.immortal.abilities.barrier, "k"],
  [SC2.UNITS.disruptor.abilities.purificationNova, "k"],
  [SC2.UNITS.phoenix.abilities.gravitonBeam, "k"],
  [SC2.UNITS.phoenix.abilities.gravitonBeam, "p"],
  [SC2.UNITS.voidRay.abilities.prismaticAlignment, "k"],
  [SC2.UNITS.oracle.abilities.activatePulsarBeam, "k"],
  [SC2.UNITS.oracle.abilities.deactivatePulsarBeam, "p"],
  [SC2.UNITS.oracle.abilities.revelation, "["],
  [SC2.UNITS.oracle.abilities.stasisWard, "'"],
  [SC2.UNITS.carrier.abilities.trainInterceptor, "k"],
  [SC2.UNITS.carrier.abilities.trainInterceptor, "["],
  [SC2.UNITS.mothership.abilities.timeWarp, "k"],
  [SC2.UNITS.mothership.abilities.massRecall, "p"],
  [SC2.UNITS.mothership.abilities.cloakingField, "["],

  // TODO hallucinate binds



  /*
   * ZERG
   */
  [SC2.UNITS.zergling, ";"],
  [SC2.UNITS.roach, "k"],
  [SC2.UNITS.drone, "p"],
  [SC2.UNITS.overlord, "/"],
  [SC2.UNITS.hydralisk, "["],
  [SC2.UNITS.queen, "'"],
  [SC2.UNITS.infestor, "'"],
  [SC2.UNITS.mutalisk, "."],
  [SC2.UNITS.corruptor, "-"],
  [SC2.UNITS.swarmHost, "]"],
  [SC2.UNITS.viper, "="],
  [SC2.UNITS.ultralisk, "back"],

  [SC2.BUILDINGS.sporeCrawler, ";"],
  [SC2.BUILDINGS.spawningPool, "k"],
  [SC2.BUILDINGS.roachWarren, "p"],
  [SC2.BUILDINGS.extractor, "/"],
  [SC2.BUILDINGS.spineCrawler, "["],
  [SC2.BUILDINGS.evolutionChamber, "'"],
  [SC2.BUILDINGS.banelingNest, "."],
  [SC2.BUILDINGS.hatchery, "-"],
  [SC2.BUILDINGS.spire, ";"],
  [SC2.BUILDINGS.hydraliskDen, "k"],
  [SC2.BUILDINGS.infestationPit, "p"],
  [SC2.BUILDINGS.lurkerDen, "["],
  [SC2.BUILDINGS.nydusNetwork, "'"],
  [SC2.BUILDINGS.ultraliskCavern, "-"],

  [SC2.ABILITIES.burrow, "["],
  [SC2.ABILITIES.unburrow, "]"],

  [SC2.BUILDINGS.hatchery.abilities.selectLarva, ";"],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "k"],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "p"],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "/"],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "["],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "."],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "-"],
  [SC2.BUILDINGS.hatchery.abilities.selectLarva, "]"],
  [SC2.BUILDINGS.hatchery.abilities.morphLairHive, "back"],
  [SC2.BUILDINGS.spire.abilities.morphGreaterSpire, "p"],
  [SC2.BUILDINGS.nydusNetwork.abilities.nydusWorm, "k"],
  [SC2.BUILDINGS.spineCrawler.abilities.root, "k"],
  [SC2.BUILDINGS.spineCrawler.abilities.uproot, "p"],
  
  [SC2.UPGRADES.burrow, "="],
  [SC2.UPGRADES.pneumatizedCarapace, "\\"],
  [SC2.UPGRADES.meleeAttacks, ";"],
  [SC2.UPGRADES.groundCarapace, "k"],
  [SC2.UPGRADES.missileAttacks, "p"],
  [SC2.UPGRADES.flyerAttack, ";"],
  [SC2.UPGRADES.flyerCarapace, "k"],
  [SC2.UPGRADES.centrifugalHooks, ";"],
  [SC2.UPGRADES.muscularAugments, ";"],
  [SC2.UPGRADES.groovedSpines, "k"],
  [SC2.UPGRADES.neuralParasite, "k"],
  [SC2.UPGRADES.adaptiveTalons, ";"],
  [SC2.UPGRADES.seismicSpines, "k"],
  [SC2.UPGRADES.glialReconstitution, ";"],
  [SC2.UPGRADES.tunnelingClaws, "k"],
  [SC2.UPGRADES.metabolicBoost, ";"],
  [SC2.UPGRADES.adrenalGlands, "k"],
  [SC2.UPGRADES.anabolicSynthesis, ";"],
  [SC2.UPGRADES.chitinousPlating, "k"],

  [SC2.UNITS.baneling.abilities.explode, "k"],
  [SC2.UNITS.baneling.abilities.disableStructureAttack, "/"],
  [SC2.UNITS.baneling.abilities.enableStructureAttack, "-"],
  [SC2.UNITS.corruptor.abilities.causticSpray, "k"],
  [SC2.UNITS.corruptor.abilities.causticSpray, "["],
  [SC2.UNITS.corruptor.abilities.morphBroodLord, "p"],
  [SC2.UNITS.hydralisk.abilities.morphLurker, "p"],
  [SC2.UNITS.infestor.abilities.fungalGrowth, "k"],
  [SC2.UNITS.infestor.abilities.microbialShroud, "p"],
  [SC2.UNITS.infestor.abilities.neuralParasite, "/"],
  [SC2.UNITS.lurker.abilities.burrow, "k"],
  [SC2.UNITS.lurker.abilities.unburrow, "p"],
  [SC2.UNITS.lurker.abilities.holdFire, "/"],
  [SC2.UNITS.lurker.abilities.release, "["],
  [SC2.UNITS.overlord.abilities.mutateVentralSacs, "k"],
  [SC2.UNITS.overlord.abilities.morphToOverseer, "p"],
  [SC2.UNITS.overlord.abilities.load, "["],
  [SC2.UNITS.overlord.abilities.generateCreep, "]"],
  [SC2.UNITS.overlord.abilities.stopGeneratingCreep, "-"],
  [SC2.UNITS.overseer.abilities.oversight, "k"],
  [SC2.UNITS.overseer.abilities.cancelOversight, "p"],
  [SC2.UNITS.overseer.abilities.contaminate, "["],
  [SC2.UNITS.overseer.abilities.changeling, "'"],
  [SC2.UNITS.queen.abilities.transfusion, "k"],
  [SC2.UNITS.queen.abilities.creepTumor, "p"],
  [SC2.UNITS.queen.abilities.injectLarva, "/"],
  [SC2.UNITS.roach.abilities.morphRavager, "p"],
  [SC2.UNITS.ravager.abilities.corrosiveBile, "k"],
  [SC2.UNITS.ravager.abilities.corrosiveBile, "p"],
  [SC2.UNITS.swarmHost.abilities.spawnLocusts, "k"],
  [SC2.UNITS.locust.abilities.swoop, "k"],
  [SC2.UNITS.viper.abilities.blindingCloud, "k"],
  [SC2.UNITS.viper.abilities.parasiticBomb, "p"],
  [SC2.UNITS.viper.abilities.abduct, "["],
  [SC2.UNITS.viper.abilities.consume, "'"],



  /*
   * Groups
   */
  [SC2.CONTROL_GROUPS[1].get, "j"],
  [SC2.CONTROL_GROUPS[2].get, "o"],
  [SC2.CONTROL_GROUPS[3].get, "l"],
  [SC2.CONTROL_GROUPS[4].get, "i"],
  [SC2.CONTROL_GROUPS[5].get, "m"],
  [SC2.CONTROL_GROUPS[6].get, "h"],
  [SC2.CONTROL_GROUPS[7].get, "n"],
  [SC2.CONTROL_GROUPS[8].get, "b"],
  [SC2.CONTROL_GROUPS[9].get, "g"],
  [SC2.CONTROL_GROUPS[10].addSteal, ","],
  [SC2.LOCATIONS[1].get, "0"],
  [SC2.LOCATIONS[2].get, "9"],
  [SC2.LOCATIONS[3].get, "8"],
  [SC2.LOCATIONS[4].get, "u"],
]);
